# Generated by Django 3.0.7 on 2020-07-23 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Director', models.CharField(max_length=30)),
                ('Cast_I', models.CharField(max_length=30)),
                ('Cast_II', models.CharField(max_length=30)),
                ('Name', models.TextField()),
                ('ReleaseYear', models.CharField(max_length=4)),
                ('ImdbRating', models.CharField(max_length=2)),
                ('Genre', models.TextField(null=True)),
            ],
        ),
    ]
