# Generated by Django 3.0.7 on 2020-07-28 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20200728_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='Language',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
