# Generated by Django 3.0.7 on 2020-07-31 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20200728_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='Available',
            field=models.TextField(default='Not available'),
            preserve_default=False,
        ),
    ]
