# Generated by Django 3.0.7 on 2020-07-31 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_movies_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='ImdbRating',
            field=models.CharField(max_length=3),
        ),
    ]
