# Generated by Django 3.0.7 on 2020-07-31 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_auto_20200731_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='Available',
        ),
        migrations.AddField(
            model_name='movies',
            name='Availbility',
            field=models.TextField(null=True),
        ),
    ]
