# Generated by Django 3.0.7 on 2020-08-26 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_profile_profilelinked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Name',
        ),
    ]
