# Generated by Django 3.0.7 on 2020-08-26 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0010_auto_20200826_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Watch_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_later', to='movie.Movies'),
        ),
    ]
