# Generated by Django 3.0.7 on 2020-08-26 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0012_auto_20200826_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Disliked_movies',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Liked_movies',
        ),
    ]
