# Generated by Django 3.0.7 on 2020-07-23 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('release_year', models.CharField(max_length=10)),
                ('director', models.CharField(max_length=50)),
                ('actor', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=30)),
                ('password', models.CharField(max_length=20)),
                ('birthday', models.DateField()),
                ('age', models.DecimalField(decimal_places=0, max_digits=3)),
                ('CheckedIn', models.BooleanField()),
            ],
        ),
    ]
