# Generated by Django 3.0.7 on 2020-06-21 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('release_year', models.CharField(max_length=10)),
                ('director', models.CharField(max_length=50)),
                ('actor', models.CharField(max_length=50)),
            ],
        ),
    ]
