# Generated by Django 3.0.7 on 2020-06-27 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=30)),
                ('password', models.TextField()),
                ('birthday', models.DateTimeField()),
                ('age', models.DecimalField(decimal_places=0, max_digits=5)),
                ('isChecked', models.BooleanField(null=True)),
            ],
        ),
    ]
