# Generated by Django 3.0.7 on 2020-06-27 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0002_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.TextField(max_length=20),
        ),
    ]
