# Generated by Django 3.0.7 on 2020-06-27 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0005_auto_20200627_1158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='isChecked',
            new_name='isCheckedIn',
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(),
        ),
    ]
