# Generated by Django 3.0.7 on 2020-06-27 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0007_auto_20200627_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(),
        ),
    ]
