# Generated by Django 3.0.7 on 2020-06-27 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0008_auto_20200627_1220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='isCheckedIn',
            new_name='CheckedIn',
        ),
    ]
