# Generated by Django 3.0.7 on 2020-06-27 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0009_auto_20200627_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='CheckedIn',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
