# Generated by Django 3.0.7 on 2020-06-27 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0010_auto_20200627_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='CheckedIn',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
